#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
# mysql
export PATH="/usr/local/mysql/bin:$PATH"

# peco
export PATH="/usr/local/Cellar/peco/0.2.5/bin:$PATH"

# scala
export SCALA_HOME="/usr/local/bin/scala"
export PATH="$SCALA_HOME/bin:$PATH"

# ruby 
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init - zsh)"

# python
export PATH="/usr/local/share/python:$PATH"

# docker
#export DOCKER_HOST=tcp://192.168.59.103:2376
#export DOCKER_CERT_PATH=/Users/miyajimatakeshi/.boot2docker/certs/boot2docker-vm
#export DOCKER_TLS_VERIFY=1

# nodebrew
export PATH="$HOME/.nodebrew/current/bin:$PATH"
